<?xml version="1.0"?>
<robot name="shl-1" xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:arg name="wheel_radius" default="0.0825"/>
  <xacro:arg name="wheel_width"  default="0.07"/>
  <xacro:arg name="wheelbase_L"  default="0.54"/>
  <xacro:arg name="track_W"      default="0.53"/>
  <xacro:arg name="wheel_z"      default="0.0"/>
  <xacro:arg name="wheel_mass"   default="0.8"/>
  <xacro:arg name="use_inertia"  default="true"/>
  <xacro:arg name="drive_joint_damping" default="0.01"/>
  <xacro:arg name="steer_joint_damping" default="0.2"/>

  <xacro:property name="WHEEL_RADIUS" value="$(arg wheel_radius)"/>
  <xacro:property name="WHEEL_WIDTH"  value="$(arg wheel_width)"/>
  <xacro:property name="WHEELBASE_L"  value="$(arg wheelbase_L)"/>
  <xacro:property name="TRACK_W"      value="$(arg track_W)"/>
  <xacro:property name="WHEEL_Z"      value="$(arg wheel_z)"/>
  <xacro:property name="WHEEL_MASS"   value="$(arg wheel_mass)"/>
  <xacro:property name="STEER_D"      value="$(arg steer_joint_damping)"/>
  <xacro:property name="DRIVE_D"      value="$(arg drive_joint_damping)"/>
  <xacro:property name="USE_INERTIA"  value="$(arg use_inertia)"/>

  <xacro:property name="x_f" value="${WHEELBASE_L/2.0}"/>
  <xacro:property name="x_m" value="${0.0}"/>
  <xacro:property name="x_r" value="${-WHEELBASE_L/2.0}"/>
  <xacro:property name="y_l" value="${TRACK_W/2.0}"/>
  <xacro:property name="y_r" value="${-TRACK_W/2.0}"/>

  <material name="black"><color rgba="0 0 0 1" /></material>
  <material name="light_black"><color rgba="0.1 0.1 0.1 1" /></material>
  <material name="aluminum"><color rgba="0.8 0.8 0.8 1.0"/></material>
  <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
  <material name="white"><color rgba="0.95 0.95 0.95 1"/></material>
  <material name="blue"><color rgba="0.0 0.5 1.0 1"/></material>
  <material name="zed2_mat"><color rgba="0.25 0.25 0.25 0.99"/></material>

  <xacro:macro name="sd_wheel" params="name parent x y z">
    <link name="${name}_horizontal_arm">
      <inertial>
        <mass value="0.3"/>
        <xacro:if value="${y > 0}"><origin xyz="0 0.05 0"/></xacro:if>
        <xacro:unless value="${y > 0}"><origin xyz="0 -0.05 0"/></xacro:unless>
        <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
      </inertial>
      <visual>
        <xacro:if value="${y > 0}"><origin xyz="0 0.05 0"/></xacro:if>
        <xacro:unless value="${y > 0}"><origin xyz="0 -0.05 0"/></xacro:unless>
        <geometry><box size="0.04 0.1 0.04"/></geometry>
        <material name="light_black"/>
      </visual>
      <collision>
        <xacro:if value="${y > 0}"><origin xyz="0 0.05 0"/></xacro:if>
        <xacro:unless value="${y > 0}"><origin xyz="0 -0.05 0"/></xacro:unless>
        <geometry><box size="0.04 0.1 0.04"/></geometry>
      </collision>
    </link>
    <joint name="${name}_horizontal_arm_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}_horizontal_arm"/>
      <xacro:if value="${y > 0}"><origin xyz="${x} 0.169 ${z}" rpy="0 0 0"/></xacro:if>
      <xacro:unless value="${y > 0}"><origin xyz="${x} -0.169 ${z}" rpy="0 0 0"/></xacro:unless>
    </joint>
    <link name="${name}_vertical_upright">
      <inertial>
        <mass value="0.5"/>
        <origin xyz="0 0 -0.125"/>
        <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-4"/>
      </inertial>
      <visual>
        <origin xyz="0 0 -0.125"/>
        <geometry><box size="0.04 0.04 0.25"/></geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 -0.125"/>
        <geometry><box size="0.04 0.04 0.25"/></geometry>
      </collision>
    </link>
    <joint name="${name}_steer_joint" type="revolute">
      <parent link="${name}_horizontal_arm"/>
      <child  link="${name}_vertical_upright"/>
      <xacro:if value="${y > 0}"><origin xyz="0 0.1 0" rpy="0 0 0"/></xacro:if>
      <xacro:unless value="${y > 0}"><origin xyz="0 -0.1 0" rpy="0 0 0"/></xacro:unless>
      <axis xyz="0 0 1"/>
      <limit lower="-1.5708" upper="1.5708" effort="20" velocity="6.28"/>
      <dynamics damping="${STEER_D}"/>
    </joint>
    <link name="${name}_wheel">
      <xacro:if value="${USE_INERTIA}">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="${WHEEL_MASS}"/>
          <inertia ixx="${0.5*WHEEL_MASS*WHEEL_RADIUS*WHEEL_RADIUS}"
                   iyy="${0.5*WHEEL_MASS*WHEEL_RADIUS*WHEEL_RADIUS}"
                   izz="${0.5*WHEEL_MASS*WHEEL_RADIUS*WHEEL_RADIUS}"
                   ixy="0" ixz="0" iyz="0"/>
        </inertial>
      </xacro:if>
      <visual>
        <origin xyz="0 0 0" rpy="-1.57079632679 0 0"/>
        <geometry>
          <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="-1.57079632679 0 0"/>
        <geometry>
          <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_drive_joint" type="continuous">
      <parent link="${name}_vertical_upright"/>
      <child  link="${name}_wheel"/>
      <xacro:if value="${y > 0}"><origin xyz="0 0.0575 -0.25" rpy="0 0 0"/></xacro:if>
      <xacro:unless value="${y > 0}"><origin xyz="0 -0.0575 -0.25" rpy="0 0 0"/></xacro:unless>
      <axis xyz="0 1 0"/>
      <dynamics damping="${DRIVE_D}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="lidar_mast_pillar" params="name parent x y">
    <link name="${name}_pillar_link">
      <inertial>
        <mass value="0.2"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="1e-4"/>
      </inertial>
      <visual>
        <geometry><cylinder radius="0.015" length="0.396"/></geometry>
        <material name="aluminum"/>
      </visual>
      <collision>
        <geometry><cylinder radius="0.015" length="0.396"/></geometry>
      </collision>
    </link>
    <joint name="${name}_pillar_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}_pillar_link"/>
      <origin xyz="${x} ${y} 0.5255" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="lidar_mast" params="parent">
    <link name="lidar_plate_link">
      <inertial>
        <mass value="0.5"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.004" ixy="0" ixz="0" iyy="0.0075" iyz="0" izz="0.011"/>
      </inertial>
      <visual>
        <geometry><box size="0.16 0.25 0.01"/></geometry>
        <material name="aluminum"/>
      </visual>
      <collision>
        <geometry><box size="0.25 0.25 0.01"/></geometry>
      </collision>
    </link>
    <joint name="lidar_plate_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="lidar_plate_link"/>
      <origin xyz="0.013 0 0.7285" rpy="0 0 0"/>
    </joint>
    <xacro:lidar_mast_pillar name="front_left"  parent="${parent}" x="0.08" y="0.1"/>
    <xacro:lidar_mast_pillar name="front_right" parent="${parent}" x="0.08" y="-0.1"/>
    <xacro:lidar_mast_pillar name="rear_left"   parent="${parent}" x="-0.06" y="0.1"/>
    <xacro:lidar_mast_pillar name="rear_right"  parent="${parent}" x="-0.06" y="-0.1"/>
  </xacro:macro>

  <xacro:macro name="armario_support_pillar" params="name parent x y">
    <link name="${name}_support_pillar_link">
      <inertial>
        <mass value="1.5"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.001"/>
      </inertial>
      <visual>
        <geometry><cylinder radius="0.01" length="0.08"/></geometry>
        <material name="aluminum"/>
      </visual>
      <collision>
        <geometry><cylinder radius="0.01" length="0.08"/></geometry>
      </collision>
    </link>
    <joint name="${name}_support_pillar_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}_support_pillar_link"/>
      <origin xyz="${x} ${y} 0.13" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="ultrasound_sensor" params="name parent x y yaw z_pos:=-0.01">
    <link name="base_ultrasound${name}">
      <inertial>
        <mass value="0.02"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" />
        <geometry><cylinder length="0.005" radius="0.01" /></geometry>
        <material name="white" />
      </visual>
      <collision>
        <origin xyz="0 0 0" />
        <geometry><cylinder length="0.05" radius="0.03" /></geometry>
      </collision>
    </link>
    <joint name="ultrasound${name}_link_joint" type="fixed">
      <parent link="${parent}" />
      <child link="base_ultrasound${name}" />
      <origin rpy="0 1.5707 ${yaw}" xyz="${x} ${y} ${z_pos}" />
    </joint>
  </xacro:macro>

  <xacro:macro name="front_bumper" params="parent">
    <link name="bumper_holder_left_link">
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
      </inertial>
      <visual>
        <origin xyz="0.05 0 0"/>
        <geometry><box size="0.1 0.03 0.03"/></geometry>
        <material name="light_black"/>
      </visual>
      <visual>
        <origin xyz="0.1 0 -0.1"/>
        <geometry><box size="0.03 0.03 0.2"/></geometry>
        <material name="light_black"/>
      </visual>
    </link>
    <joint name="bumper_holder_left_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="bumper_holder_left_link"/>
      <origin xyz="0.277 0.15 -0.06"/>
    </joint>
    <link name="bumper_holder_right_link">
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
      </inertial>
      <visual>
        <origin xyz="0.05 0 0"/>
        <geometry><box size="0.1 0.03 0.03"/></geometry>
        <material name="light_black"/>
      </visual>
      <visual>
        <origin xyz="0.1 0 -0.1"/>
        <geometry><box size="0.03 0.03 0.2"/></geometry>
        <material name="light_black"/>
      </visual>
    </link>
    <joint name="bumper_holder_right_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="bumper_holder_right_link"/>
      <origin xyz="0.277 -0.15 -0.06"/>
    </joint>
    <link name="bumper_bar_link">
      <inertial>
        <mass value="1.0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
      </inertial>
      <visual>
        <geometry><box size="0.04 0.6 0.04"/></geometry>
        <material name="aluminum"/>
      </visual>
    </link>
    <joint name="bumper_bar_joint" type="fixed">
      <parent link="bumper_holder_left_link"/>
      <child link="bumper_bar_link"/>
      <origin xyz="0.115 -0.15 -0.2" rpy="0 1.5707 0"/>
    </joint>
  </xacro:macro>

  <link name="base_link">
    <inertial>
      <mass value="15.0"/>
      <inertia ixx="0.22" ixy="0.0" ixz="0.0" iyy="0.41" iyz="0.0" izz="0.51"/>
    </inertial>
    <visual>
      <geometry><box size="0.54 0.338 0.202"/></geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry><box size="0.54 0.338 0.202"/></geometry>
    </collision>
  </link>

  <link name="base_footprint"></link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.3315" rpy="0 0 0"/>
  </joint>

  <link name="base_battery">
    <inertial>
      <mass value="7.0"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.05" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.12"/>
    </inertial>
    <visual>
      <geometry><mesh filename="package://rse_shl1_description/meshes/bases/trapezoid_battery.stl"/></geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry><mesh filename="package://rse_shl1_description/meshes/bases/trapezoid_battery.stl"/></geometry>
    </collision>
  </link>
  <joint name="base_battery_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_battery"/>
    <origin xyz="-0.003 0 -0.15"/>
  </joint>

  <link name="armario">
    <inertial>
      <mass value="10.0"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.57" ixy="0.0" ixz="0.0" iyy="0.77" iyz="0.0" izz="0.98"/>
    </inertial>
    <visual>
      <geometry><box size="0.715 0.49 0.655"/></geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="black"/>
    </visual>
    <collision>
      <geometry><box size="0.715 0.49 0.655"/></geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
  </link>
  <joint name="armario_link_joint" type="fixed">
    <parent link="base_link"/>
    <child link="armario"/>
    <origin rpy="0 0 0" xyz="0.002 0 0.5025 "/>
  </joint>

  <link name="base_laser">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0"/>
      <geometry><cylinder length="0.05" radius="0.03"/></geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry><cylinder length="0.05" radius="0.03"/></geometry>
    </collision>
  </link>
  <joint name="laser_link_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_laser"/>
    <origin rpy="0 0 3.141593" xyz="0.299 0 0.12"/>
  </joint>
  
  <xacro:lidar_mast parent="armario"/>
  
  <link name="rslidar">
    <visual>
      <origin xyz="0 0 -0.05" rpy="1.5708 0 1.5708"/>
      <geometry><mesh filename="package://rse_shl1_description/meshes/sensors/Helios.stl" scale="0.001 0.001 0.001"/></geometry>
      <material name="light_black"/>
    </visual>
    <collision>
      <origin xyz="0 0 -0.05" rpy="1.5708 0 1.5708"/>
      <geometry><mesh filename="package://rse_shl1_description/meshes/sensors/Helios.stl" scale="0.001 0.001 0.001"/></geometry>
    </collision>
    <inertial>
      <mass value="1.2"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0015" ixy="0" ixz="0" iyy="0.0015" iyz="0" izz="0.0014"/>
    </inertial>
  </link>
  <joint name="rslidar_joint" type="fixed">
    <parent link="lidar_plate_link"/>
    <child link="rslidar"/>
    <origin xyz="0 0 0.055"/>
  </joint>
  <link name="base_imu_link">
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry><box size="0.06 0.04 0.02" /></geometry>
      <material name="blue" />
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry><box size="0.06 0.04 0.02" /></geometry>
    </collision>
  </link>
  <joint name="imu_link_joint" type="fixed">
    <parent link="base_link" />
    <child link="base_imu_link" />
    <origin xyz="0.127 0 0.02" />
  </joint>

  <link name="gnss_bar_link">
    <inertial>
      <mass value="1.7"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.00052" ixy="0" ixz="0" iyy="0.156" iyz="0" izz="0.157"/>
    </inertial>
    <visual>
      <geometry><box size="1.05 0.06 0.01"/></geometry>
      <material name="aluminum"/>
    </visual>
    <collision>
      <geometry><box size="1.05 0.06 0.01"/></geometry>
    </collision>
  </link>
  <joint name="gnss_bar_joint" type="fixed">
    <parent link="armario"/>
    <child link="gnss_bar_link"/>
    <origin xyz="0 0 0.335"/>
  </joint>

  <link name="gnss_base">
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry><box size="0.06 0.055 0.025" /></geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry><box size="0.06 0.055 0.025" /></geometry>
    </collision>
  </link>
  <joint name="gnss_base_joint" type="fixed">
    <parent link="gnss_bar_link"/>
    <child link="gnss_base"/>
    <origin xyz="-0.5175 0 0.0175"/>
  </joint>

  <link name="gnss_heading">
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry><box size="0.06 0.055 0.025" /></geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry><box size="0.06 0.055 0.025" /></geometry>
    </collision>
  </link>
  <joint name="gnss_heading_joint" type="fixed">
    <parent link="gnss_bar_link"/>
    <child link="gnss_heading"/>
    <origin xyz="0.5175 0 0.0175"/>
  </joint>

  <link name="zed2_camera_center">
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry><mesh filename="package://rse_shl1_description/meshes/sensors/zed2.stl"/></geometry>
      <material name="zed2_mat"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry><mesh filename="package://rse_shl1_description/meshes/sensors/zed2.stl"/></geometry>
    </collision>
  </link>
  <joint name="zed2_camera_center_joint" type="fixed">
    <parent link="armario"/>
    <child link="zed2_camera_center"/>
    <origin rpy="0.0 0.0 0.0" xyz="0.1 0.0 0.7075"/>
  </joint>
  
  <link name="zed2_left_camera_frame"/>
  <joint name="zed2_left_camera_joint" type="fixed">
    <parent link="zed2_camera_center"/>
    <child link="zed2_left_camera_frame"/>
    <origin rpy="0 0 0" xyz="0 0.06 0"/>
  </joint>
  
  <link name="zed2_left_camera_optical_frame"/> 
  <joint name="zed2_left_camera_optical_joint" type="fixed">
    <origin rpy="-1.57079632679 0.0 -1.57079632679" xyz="0 0 0"/>
    <parent link="zed2_left_camera_frame"/>
    <child link="zed2_left_camera_optical_frame"/>
  </joint>
  
  <link name="zed2_right_camera_frame"/>
  <joint name="zed2_right_camera_joint" type="fixed">
    <parent link="zed2_camera_center"/>
    <child link="zed2_right_camera_frame"/>
    <origin rpy="0 0 0" xyz="0 -0.06 0"/>
  </joint>

  <link name="zed2_right_camera_optical_frame"/>
  <joint name="zed2_right_camera_optical_joint" type="fixed">
    <origin rpy="-1.57079632679 0.0 -1.57079632679" xyz="0 0 0"/>
    <parent link="zed2_right_camera_frame"/>
    <child link="zed2_right_camera_optical_frame"/>
  </joint>

  <xacro:front_bumper parent="base_link"/>

  <xacro:armario_support_pillar name="fl" parent="base_link" x="0.19" y="0.12"/>
  <xacro:armario_support_pillar name="fr" parent="base_link" x="0.19" y="-0.12"/>
  <xacro:armario_support_pillar name="rl" parent="base_link" x="-0.24" y="0.12"/>
  <xacro:armario_support_pillar name="rr" parent="base_link" x="-0.24" y="-0.12"/>

  <xacro:ultrasound_sensor name="1"  parent="base_link" x="0.27"  y="0.083"   yaw="0.0"/>
  <xacro:ultrasound_sensor name="2"  parent="base_link" x="0.27"  y="-0.083"  yaw="0.0"/>
  <xacro:ultrasound_sensor name="4"  parent="base_link" x="0.109"  y="-0.167" yaw="-1.57"/>
  <xacro:ultrasound_sensor name="5"  parent="base_link" x="-0.151" y="-0.167" yaw="-1.57"/>
  <xacro:ultrasound_sensor name="7"  parent="base_link" x="-0.2681" y="-0.1185" yaw="3.14"/>
  <xacro:ultrasound_sensor name="8"  parent="base_link" x="-0.2681" y="0.1185"  yaw="3.14"/>
  <xacro:ultrasound_sensor name="10" parent="base_link" x="-0.151" y="0.167"  yaw="1.57"/>
  <xacro:ultrasound_sensor name="11" parent="base_link" x="0.109"  y="0.167"  yaw="1.57"/>

  <xacro:sd_wheel name="fl" parent="base_link" x="${x_f}" y="${y_l}" z="${WHEEL_Z}"/>
  <xacro:sd_wheel name="fr" parent="base_link" x="${x_f}" y="${y_r}" z="${WHEEL_Z}"/>
  <xacro:sd_wheel name="ml" parent="base_link" x="${x_m}" y="${y_l}" z="${WHEEL_Z}"/>
  <xacro:sd_wheel name="mr" parent="base_link" x="${x_m}" y="${y_r}" z="${WHEEL_Z}"/>
  <xacro:sd_wheel name="rl" parent="base_link" x="${x_r}" y="${y_l}" z="${WHEEL_Z}"/>
  <xacro:sd_wheel name="rr" parent="base_link" x="${x_r}" y="${y_r}" z="${WHEEL_Z}"/>

  <!-- ========================================= -->
  <!-- ROS2_CONTROL CONFIGURATION FOR GAZEBO     -->
  <!-- ========================================= -->
  
  <ros2_control name="GazeboSimSystem" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>
    
    <!-- Front Left Wheel -->
    <joint name="fl_steer_joint">
      <command_interface name="position">
        <param name="min">-1.5708</param>
        <param name="max">1.5708</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="fl_drive_joint">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    
    <!-- Front Right Wheel -->
    <joint name="fr_steer_joint">
      <command_interface name="position">
        <param name="min">-1.5708</param>
        <param name="max">1.5708</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="fr_drive_joint">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    
    <!-- Middle Left Wheel -->
    <joint name="ml_steer_joint">
      <command_interface name="position">
        <param name="min">-1.5708</param>
        <param name="max">1.5708</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="ml_drive_joint">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    
    <!-- Middle Right Wheel -->
    <joint name="mr_steer_joint">
      <command_interface name="position">
        <param name="min">-1.5708</param>
        <param name="max">1.5708</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="mr_drive_joint">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    
    <!-- Rear Left Wheel -->
    <joint name="rl_steer_joint">
      <command_interface name="position">
        <param name="min">-1.5708</param>
        <param name="max">1.5708</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rl_drive_joint">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    
    <!-- Rear Right Wheel -->
    <joint name="rr_steer_joint">
      <command_interface name="position">
        <param name="min">-1.5708</param>
        <param name="max">1.5708</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rr_drive_joint">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <!-- ========================================= -->
  <!-- GAZEBO PLUGIN FOR ROS2_CONTROL            -->
  <!-- ========================================= -->
  
  <gazebo>
    <plugin filename="gz_ros2_control-system" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
      <parameters>$(find rse_shl1_swerve_controller)/config/swerve_controller.yaml</parameters>
      <parameters>$(find rse_shl1_control)/config/controllers.yaml</parameters>
      <ros>
        <namespace></namespace>
        <remapping>/clock:=/clock</remapping>
        <parameter name="use_sim_time" type="bool">true</parameter>
      </ros>
    </plugin>
  </gazebo>

</robot>